### ISSUE TITLE
Project setup

### ISSUE THREAD

**Issue by juanhurtado10** [kommitters/mintacoin#1]
ℹ️ This issue is an Epic 🎯

## Objective

Prepare a brand new Elixir + Phoenix project and release an initial version.

## Checklist
- [ ] New project structure
- [ ] Add OSPO docs and related policies
- [ ] Setup CI with Github actions
